{{- $files := .Files -}}
{{ range .Values.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postfix.fullname" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
data:
  {{ base .path }}: |-
    {{- tpl ($files.Get .path) $ | nindent 4 -}}
{{- end -}}
