{{- if .Files.Glob .Values.tlsCertificateFile -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "postfix.fullname" . }}-certificate
  namespace: {{ .Release.Namespace }}
data:
  tls.chain: {{ .Files.Get .Values.tlsCertificateChainFile | b64enc }}
  tls.crt: {{ .Files.Get .Values.tlsCertificateFile | b64enc }}
  tls.key: {{ .Files.Get .Values.tlsCertificateKeyFile | b64enc }}
{{- end -}}
