apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfixadmin
  namespace: mailserver
spec:
  selector:
    matchLabels:
      app: mailserver
      tier: postfixadmin
  template:
    metadata:
      labels:
        app: mailserver
        tier: postfixadmin
        logType: apache
    spec:
      containers:
      - name: postfixadmin
        image: technicalguru/mailserver-postfixadmin
        imagePullPolicy: IfNotPresent
        env:
        - name: PFA_DB_HOST
          value: "mariadb"
        - name: PFA_DB_NAME
          value: "mail"
        - name: PFA_DB_USER
          value: "postfix"
        - name: PFA_DB_PASS
          value: "<my-mariadb-postfix-password>"
        - name: PFA_SETUP_PASS
          value: "<my-mariadb-root-password>"
        - name: PFA_POSTFIX_SERVER
          value: "postfix"
        - name: PFA_POSTFIX_PORT
          value: "25"
        - name: PFA_ABUSE_EMAIL
          value: "<my-abuse-email-address>"
        - name: PFA_HOSTMASTER_EMAIL
          value: "<my-hostmaster-email-address>"
        - name: PFA_POSTMASTER_EMAIL
          value: "<my-postmaster-email-address>"
        - name: PFA_WEBMASTER_EMAIL
          value: "<my-webmaster-email-address>"
        ports:
        - containerPort: 80
          name: http
    
