# Default values for amavis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

# $replicaCount - the number of replicas in the deployment to create
replicaCount: 1

# $image            - definition of docker image
# $image.repository - the image name (without tag)
# $image.pullPolicy - The pull policy for the image
image:
  repository: technicalguru/mailserver-amavis
  pullPolicy: IfNotPresent

# $additionalLabels - additional labels to attach to a pod
additionalLabels: {}
#  labelKey: labelValue

#####################
# Service settings
#####################
# $service.port - the incoming service port
service:
  port: 10024

# $resources - additional resource requirements
resources: {}

# $affinityLabel - the key of the node label for affinity stickiness
# $environment   - the node label the pod is running on (dev, uat, prod)
affinityLabel: "mailserver/environment"
environment: "dev"

#####################
# Mail settings
#####################
# $defaultDomain     - default mail domain
# $relayHostname     - name of host for Amavis mail scanning (optional)
# $relayPort         - relay port for Amavis mail scanning
# $virusAdminEmail   - e-mail of admin to be informed when viruses were quarantined
defaultDomain: ""
relayHostname: "postfix-internal"
relayPort: "10025"
virusAdminEmail: ""

###########################
# Additional customization 
###########################
# $configfiles - list of config file definitions
# $configfiles[].name - unique name for config definition
# $configfiles[].mountPath - path of file in pod to mount at
# $configfiles[].path - the config file (must be accessible within HELM chart)
configFiles: {}
#- name: example1
#  mountPath: /etc/spamassassin/x10-example.cf
#  path: example1.cf
#- name: example2
#  mountPath: /etc/spamassassin/x20-example.cf
#  path: example2.cf
